version: '3.9'

services:

  app:
    build:
      args:
        DEBUG_BUILD: ${DEBUG}

  geodb:
    image: postgis/postgis:12-3.0
    restart: unless-stopped
    volumes:
      - geodb_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${GEODB_DB}
      POSTGRES_USER: ${GEODB_USER}
      POSTGRES_PASSWORD: ${GEODB_PASSWORD}
    ports:
      - ${HOST_GEODB_PORT}:5432

volumes:
  geodb_data:
